### ISSUE TITLE
emailID

### ISSUE THREAD

**Issue by benjo2410** [JakeCooper/OnePlusTwoBot#1]
"emailID is not defined" shows after "curling"

**Comment by JakeCooper** [comment]
That occurs if you haven't setup the API key properly, or the API expires, or the call fails. I'll add a check for that in a couple hours when I'm awake again.

**Comment by benjo2410** [comment]
I'm pretty sure the API is set up properly. Why would the call fail?

**Comment by JakeCooper** [comment]
Not sure, but I'll have a look in a little while :D.

**Comment by haim-ari** [comment]
Same here

Traceback (most recent call last):
  File "./OnePlusTwo.py", line 35, in <module>
    if emailID is None:
NameError: name 'emailID' is not defined

from API Doc:
Fetch Mailinator Inbox: 
   https://api.mailinator.com/api/inbox?to=<INBOX>&token=19bab8baa4b84ceda2526b55ad7b11fe 
Fetch Private Inbox: 
   https://api.mailinator.com/api/inbox?token=19bab8baa4b84ceda2526b55ad7b11fe 
Fetch Email: 
   https://api.mailinator.com/api/email?msgid= <MSGID>&token=19bab8baa4b84ceda2526b55ad7b11fe

**Comment by DennyWeinberg** [comment]
Replace [...]&email={{0}}%40ma[...] by [...]&email={0}%40ma[...]
And i changed the "_=" variable. But i don't know if it is needed.
My code works now. I had the same problem as you...

Also you can improve the code by doing this:

```
emailID = None
for i in range(0, 5):
    response = requests.get(mailinatorInbox)
    json_data = json.loads(response.text)

    for message in json_data["messages"]:
        if message["subject"] == "Confirm your email":
            emailID = message["id"]

    if emailID:
        break

    #print('sleep')
    time.sleep(1)

if not emailID:
    continue
```

EDIT:
It is possible that you get this message:
"Oops, a lot of people are trying to sign up right now, please try again in a few minutes!"
 :p

**Comment by haim-ari** [comment]
the delay is not enough or quota problem:
i get:
{u'error': u'rate limiter reached'}

**Comment by JakeCooper** [comment]
The above error is the result of you hitting you mailinator personal cap.

**Comment by JakeCooper** [comment]
and @DennyWeinberg, submit a pull request and I'll merge it in.

**Comment by DennyWeinberg** [comment]
Sorry i never done it and i don't know how to do it. And no time... You can commit the changes for me?

**Comment by haim-ari** [comment]
For now:
1. change sleep to 60 secs or more
2. replace you public ip if you can

add this in case it happens again (and raise sleep more)

```
    if "rate" in json_data["error"]:
            continue
```

**Comment by oxisharke** [comment]
sorry but I didn't achieve to a correct code with modification, can someone send me the full code working please :/ ?

**Comment by Siddharaj6010** [comment]
I tried what @DennyWeinberg suggested and now mine is working. Thanks a lot JakeCooper and DennyWeinberg.

**Comment by oxicuze** [comment]
sorry but I didn't achieve to a correct code with modification, can someone send me the full code working please :/ ? @Siddharaj6010 please ?

**Comment by Siddharaj6010** [comment]
I have tried to fork it and created Pull request @JakeCooper. I am new to Github so parden me if I made any mistake. @oxicuze  meanwhile you can copy code from this link https://github.com/Siddharaj6010/OnePlusTwoBot/blob/3ec06473538216bff200c46e81c021783cbb5608/OnePlusTwo.py

**Comment by JakeCooper** [comment]
Request merged. Looks good :).

**Comment by DennyWeinberg** [comment]
Don't forget this: Replace [...]&email={{0}}%40ma[...] by [...]&email={0}%40ma[...]
It works without this midification? I had to do this... py3

**Comment by Siddharaj6010** [comment]
^ Mine worked without that modification.

**Comment by oxicuze** [comment]
is it working ? ( with Siddharaj6010 fork )
![screenshot_3](https://cloud.githubusercontent.com/assets/13648081/9069923/9be2c1d4-3aec-11e5-8a77-214a88b7d36f.png)

**Comment by JakeCooper** [comment]
Just committed Danny's fix. It won't work without it. Actually fails silently, my bad.

A successful call has 4 parts :
http://i.imgur.com/ttRLDD6.png

All is good now though.

**Comment by Siddharaj6010** [comment]
Thanks, I realized mine started working NOW. :-)

**Comment by DennyWeinberg** [comment]
Please remove the line 23-25
It makes no sense because of the loop.

**Comment by oxicuze** [comment]
A new error with @Siddharaj6010  commit 
![image](https://cloud.githubusercontent.com/assets/13648081/9070140/06b37142-3aee-11e5-9886-77e03d934b8b.png)

**Comment by JakeCooper** [comment]
Uhh, why did someone add a 5 range for loop? Is it really worth the redundancy to try to retrieve the email 5 times?

**Comment by oxicuze** [comment]
with the latest version : ( checked API key and kolid ) 
![image](https://cloud.githubusercontent.com/assets/13648081/9070272/f2732550-3aee-11e5-9c58-cdac0826b6d4.png)

**Comment by JakeCooper** [comment]
Yea I just had that happen as well. Can't debug it cause I gotta run, someone else is gonna need to take a crack at it.

**Comment by oxicuze** [comment]
@DennyWeinberg @Siddharaj6010  any idea ?

**Comment by yuya-iwabuchi** [comment]
@oxicuze Probably bad token.

**Comment by Siddharaj6010** [comment]
@oxicuze That error must have been caused because of personal cap on mailinator. I signed up with a new account and replaced the access token and now it is working again.

**Comment by oxicuze** [comment]
Bad token ! it's working now !

**Comment by yuya-iwabuchi** [comment]
Also "_" parameter seems to be Unix timestamp in millisecond, so it might be wiser to differentiate each requests by changing/updating it.

**Comment by oxicuze** [comment]
make a commit @Sunakujira1 !

**Comment by JakeCooper** [comment]
Closing this. If you have a new issue you can make a new one. If this one reappears just reopen it.
