### ISSUE TITLE
Python gmail click confirmation

### ISSUE THREAD

**Issue by KWAc** [JakeCooper/OnePlusTwoBot#14]
Someone can help me implement a python script to click on the confirmation mails ? 
I tried yet but I have some trouble with the imaplib :)

**Comment by oxicuze** [comment]
the same here !

**Comment by oxicuze** [comment]
![image](https://cloud.githubusercontent.com/assets/13648081/9086258/9ab9ee26-3b83-11e5-8786-0bc7207d24f1.png)
my code : 

![image](https://cloud.githubusercontent.com/assets/13648081/9086262/b541b418-3b83-11e5-8bf7-86e793d5a285.png)

**Comment by KWAc** [comment]
Put your functions before your main and not after :)

**Comment by oxicuze** [comment]
still not working ^^
http://prntscr.com/8145ct

**Comment by KWAc** [comment]
My code : 
![image](https://cloud.githubusercontent.com/assets/10263203/9086562/5fb6c07c-3b85-11e5-9392-064bdf468d59.png)

My error : 
![image](https://cloud.githubusercontent.com/assets/10263203/9086501/14be1e76-3b85-11e5-9107-db79070ac980.png)

**Comment by oxicuze** [comment]
I got the same error !

**Comment by KWAc** [comment]
Ok I find a solution

You must add different packages:

import imaplib
import string
import urllib2
import time
import email
import re
import requests

Warning : Don't forget to install requests with pip (pip install requests)
