### ISSUE TITLE
Python gmail clicker

### ISSUE THREAD

**Issue by oxicuze** [JakeCooper/OnePlusTwoBot#17]
@Kwac it isn't working
![image](https://cloud.githubusercontent.com/assets/13648081/9087737/c0d4b416-3b8c-11e5-9209-5e7efc629ec1.png)

Can you commit your code please  ?

**Comment by KWAc** [comment]
yes. in 5 min

**Comment by oxicuze** [comment]
thanks ! waiting for it :)

**Comment by KWAc** [comment]
https://github.com/KWAc/gmailClicker

I will make a pull request

**Comment by oxicuze** [comment]
I'm a lazy man :') 
![image](https://cloud.githubusercontent.com/assets/13648081/9091089/8923afd8-3b9e-11e5-8d16-8df9e9d2175c.png)
