### ISSUE TITLE
Parser error with python 3

### ISSUE THREAD

**Issue by oxicuze** [JakeCooper/OnePlusTwoBot#32]
![image](https://cloud.githubusercontent.com/assets/13648081/9119052/f02a4a30-3c74-11e5-9f10-e1522cea4d62.png)

**Comment by rajdeep26** [comment]
Hey @oxicuze I also got this error when I was entering the email address, then i tried using single quotes around the email and it worked perfectly. For example instead of just entering  neversettletwo@gmail.com enter 'neversettletwo@gmail.com'
