### ISSUE TITLE
How does one plug in the email and run the program because im still getting a message that says "SyntaxError: multiple statements found while compiling a single statement"

### ISSUE THREAD

**Issue by yanggatang** [JakeCooper/OnePlusTwoBot#34]
EMAIL = input("Email : shd0wbullet@gmail.com")
REFERAL_CODE = input("Referral Code : KJO5FM")

def dotify(string):
    if len(string) == 1:
        yield string
        return

```
for rest in dotify(string[1:]):
    yield string[0] + rest
    yield string[0] + "." + rest  
```

for email in list(dotify(EMAIL.split("@")[0].replace(".","") + "@" + EMAIL.split("@")[1])):
    requestURL = "https://invites.oneplus.net/index.php?r=share/signup&success_jsonpCallback=success_jsonpCallback&email={0}&koid={1}&_=1438677876942".format(email.replace("@", "%40"), REFERAL_CODE)
    print("Sending invite to " + email)
    res = requests.get(requestURL)
    if (res.status_code == 200):
        print("Successfully retreived response")
    else :
        print("OnePlus' servers run on hamsters. Request failed.")  
    print()
    time.sleep(5)

SyntaxError: multiple statements found while compiling a single statement

**Comment by JasonZ10** [comment]
```
EMAIL = input("Email : shd0wbullet@gmail.com")
REFERAL_CODE = input("Referral Code : KJO5FM")
```

If you want to input your email and referral code into the program manually, you should do:

```
EMAIL = "shd0wbullet@gmail.com"
REFERAL_CODE = "KJO5FM"
```

As input("Email: aaa") will just print "Email: aaa" and wait for a response from the user.
