### ISSUE TITLE
Sending - curling loop 

### ISSUE THREAD

**Issue by oxicuze** [JakeCooper/OnePlusTwoBot#4]
Even if I change the token, the script do it :

![image](https://cloud.githubusercontent.com/assets/13648081/9072968/a9ad4f66-3afe-11e5-91a6-91c3d61baa31.png)

**Comment by AwesomeJake** [comment]
Same here, something wrong with mailinator?

**Comment by JakeCooper** [comment]
Pull latest changes and it should work. There was a bracketing issue.

**Comment by oxicuze** [comment]
still not working

**Comment by oxicuze** [comment]
Do you think it can come from the api key ?

**Comment by jplarar** [comment]
try again with more time in sleep() some times onePlus takes more time to send the invites, it depends on current traffic

**Comment by oxicuze** [comment]
with sleep(20) 

![image](https://cloud.githubusercontent.com/assets/13648081/9074584/462f1854-3b0b-11e5-85c2-b9cecc947eec.png)

**Comment by jplarar** [comment]
Change apiToken in the line 47 to uppercase APITOKEN
`mailinatorMessage = "https://api.mailinator.com/api/email?id=" + emailID + "&token=" + APITOKEN`

**Comment by oxicuze** [comment]
made a commit fixing the lag
