### ISSUE TITLE
Error in line 28?

### ISSUE THREAD

**Issue by DividedByZero0** [JakeCooper/OnePlusTwoBot#7]
Tried running it, and got this: 
![screenshot 151](https://cloud.githubusercontent.com/assets/13650776/9074870/c0720c1a-3ae4-11e5-90ef-78019cf544fa.png)

Error in the code?

**Comment by AwesomeJake** [comment]
i'm having this error now as well.

**Comment by JakeCooper** [comment]
Your response is probably null. Check that your API key didn't get rate limited.
